# This is a basic workflow to help you get started with Actions

name: CD

env:
  JENKINS_HOST: https://2043-186-132-146-177.ngrok.io/ ## jenkins base url
  JENKINS_JOB_QA: test_build ## builds the HelloWorld job inside testJobs
  JENKINS_JOB_STAGING: test2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - qa

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      - if: github.ref == 'refs/heads/main'
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: ${{ env.JENKINS_JOB_STAGING }}
          jenkins-job-params: '{ "branch" : "main" }'
      - if: github.ref == 'refs/heads/qa'
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: ${{ env.JENKINS_JOB_QA }}
          jenkins-job-params: "{ 'branch' : 'qa' }"
          
