# This is a basic workflow to help you get started with Actions

name: CD

env:
  JENKINS_HOST: https://2043-186-132-146-177.ngrok.io/ 
  JENKINS_JOB_QA: test2  
  JENKINS_JOB_STAGING: test_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - qa

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      - if: github.ref == 'refs/heads/main'
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: ${{ env.JENKINS_JOB_STAGING }}
      - if: github.ref == 'refs/heads/${{secrets.BRANCH_QA}}'
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: ${{ env.JENKINS_JOB_QA }}
          jenkins-job-params: "{'branch': ${{ secrets.BRANCH_QA }}}"
          
