# This is a basic workflow to help you get started with Actions

name: CD

env:
  JENKINS_HOST: https://ce00-186-132-144-127.ngrok.io/

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - qa
jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps: 
      - if: ${{ github.ref_name == 'main'}}
        uses: GoldenspearLLC/build-jenkins-job@master
        with:
          user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          job-path: "job/test_build_qa"
          job-params: '{"branch": "develop" }'
      - name: Get job status
        run: echo "Job status is ${{ steps.job-build.outputs.job_status }}"
          
          
