# This is a basic workflow to help you get started with Actions

name: CD

env:
  JENKINS_HOST: https://2043-186-132-146-177.ngrok.io/ 
  JENKINS_JOB_QA: test2  
  JENKINS_JOB_STAGING: test_build
  BRANCH_QA: ${{secrets.BRANCH_QA}}
  BRANCH_STAGING: ${{secrets.BRANCH_STAGING}}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - qa

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      - run: echo 'refs/heads/${{env.BRANCH_QA}}'
      - run: echo 'refs/heads/${{env.BRANCH_QA}}'
      - if: ${{github.ref == 'refs/heads/${{ env.BRANCH_QA }}' }}
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: ${{ env.JENKINS_JOB_QA }}
          jenkins-job-params: '{"branch": "${{env.BRANCH_QA}}" }'
      - if: ${{ github.ref == 'refs/heads/${{ env.BRANCH_STAGING }}' }}
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: ${{ env.JENKINS_JOB_STAGING }}
          jenkins-job-params: '{"branch": "${{env.BRANCH_STAGING}}" }'
          
          
          
