# This is a basic workflow to help you get started with Actions

name: CD

env:
  JENKINS_HOST: "ce00-186-132-144-127.ngrok.io/"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - qa
jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps: 
      - if: ${{ github.ref_name == 'main'}}
        uses: alexis2013/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: "test_build_staging"           
          jenkins-job-params: '{"branch": "develop" }'

          
