# This is a basic workflow to help you get started with Actions

name: CD

env:
  JENKINS_HOST: https://c9a0-186-132-251-190.ngrok.io/
  JENKINS_JOB_QA: test_build_qa  
  JENKINS_JOB_STAGING: test_build_staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - qa
jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps: 
      - if: ${{ github.ref_name == qa}}
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: ${{ env.JENKINS_JOB_QA }}            
          jenkins-job-params: '{"branch": "${{github.ref_name}}" }'
      - if: ${{ github.ref_name == main }}
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-url: ${{ env.JENKINS_HOST }}
          jenkins-job: ${{ env.JENKINS_JOB_STAGING }}
          jenkins-job-params: '{"branch": "${{github.ref_name}}" }'
          
          
